### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by ghost** [andrey-aleshkov/selectel-storage-promise#1]
команда `start`, прописанная в `package.json`:
```json
{
"start": "node --harmony app.js"
}
```

нужно либо удалить команду из `package.json` либо добавить файл `app.js`

`npm-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle selectel-storage-promise@1.0.0~prestart: selectel-storage-promise@1.0.0
6 silly lifecycle selectel-storage-promise@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle selectel-storage-promise@1.0.0~start: selectel-storage-promise@1.0.0
8 verbose lifecycle selectel-storage-promise@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle selectel-storage-promise@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/artemtsatsin/pro/selectel-storage-promise/node_modules/.bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/heroku/bin:/usr/local/go/bin:/Users/artemtsatsin/.config/yarn/global/node_modules/.bin/:/Users/artemtsatsin/Library/Android/sdk/tools:/Users/artemtsatsin/Library/Android/sdk/platform-tools:/usr/local/go/bin:/Users/artemtsatsin/.config/yarn/global/node_modules/.bin/:/Users/artemtsatsin/Library/Android/sdk/tools:/Users/artemtsatsin/Library/Android/sdk/platform-tools
10 verbose lifecycle selectel-storage-promise@1.0.0~start: CWD: /Users/artemtsatsin/pro/selectel-storage-promise
11 silly lifecycle selectel-storage-promise@1.0.0~start: Args: [ '-c', 'node --harmony app.js' ]
12 silly lifecycle selectel-storage-promise@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle selectel-storage-promise@1.0.0~start: Failed to exec start script
14 verbose stack Error: selectel-storage-promise@1.0.0 start: `node --harmony app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid selectel-storage-promise@1.0.0
16 verbose cwd /Users/artemtsatsin/pro/selectel-storage-promise
17 error Darwin 16.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error selectel-storage-promise@1.0.0 start: `node --harmony app.js`
22 error Exit status 1
23 error Failed at the selectel-storage-promise@1.0.0 start script 'node --harmony app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the selectel-storage-promise package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node --harmony app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs selectel-storage-promise
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls selectel-storage-promise
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by andrey-aleshkov** [comment]
Thank you! Done.
